### PR TITLE
Passing content Type as function.

### PR DESCRIPTION
**Pull request by parveen1112**
We need to set ContentType of css as well as js while pushing the file on azure blob storage. We need to set the content type for each file. I have passed contentType as a function and filePath as the argument. One can pass the contentType as function and set the contentType on the basis of their file.

### CODE REVIEW

**Comment by yohanb** [comment]
Hi Parveen,
could you please also update the readme in your PR with a usage example?
Thanks

**Comment by parveen-jabong** [comment]
@yohanb Updated the README

**Comment by parveen-jabong** [comment]
@yohanb Can you please have a look. Thanks

**Comment by parveen-jabong** [comment]
Other plugins were not executing by including storage plugin were not executing since we have called the callback by compiler.

**Pull request closed without merging**
